jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Verify and analyze with SonarCloud
      run: mvn --batch-mode clean verify
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
